replicaCount: 2

image:
  repository: greenstand/treetracker-wallet-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  - name: REACT_APP_WALLET_API_ROOT
    value: "http://greenstand-treetracker-wallet-api:80"

resources: {}
