replicaCount: 2

image:
  repository: greenstand/treetracker-web-map-client
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  - name: REACT_APP_QUERY_API_ROOT
    value: "http://greenstand-treetracker-query-api:80"
  - name: REACT_APP_MAP_CONFIG_API
    value: "http://greenstand-map-config-api:80"

resources: {}
