replicaCount: 2

image:
  repository: greenstand/treetracker-contract-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

env: []
# env:
#   - name: DATABASE_URL
#     value: "postgresql://user:pass@postgres:5432/treetracker"

resources: {}
